#!/usr/bin/env bash

DIR="$(cd $( dirname $0) && pwd)"
"$DIR/make.sh"
"$DIR/tmux.sh"
"$DIR/git.sh"
"$DIR/sshfs.sh"
"$DIR/docker.sh"
"$DIR/idea.sh"
"$DIR/vscode.sh"
"$DIR/peek.sh"
"$DIR/python.sh"
"$DIR/npm.sh"
"$DIR/interface.sh"
"$DIR/gimp.sh"
"$DIR/htop.sh"
"$DIR/chrome.sh"
